### ISSUE TITLE
Unable to access jarfile /opt/seppb/sepp.jar

### ISSUE THREAD

**Issue by ca-ssiee** [purang-fintech/seppb#2]
运行java -Dpath=/opt/seppb/conf/spring.properties -jar /opt/seppb/sepp.jar &
提示错误
![image](https://user-images.githubusercontent.com/24838062/71141789-3e873d80-2250-11ea-8f0a-ad03fa7d3a71.png)

**Comment by purang-fintech** [comment]
操作常识不足，非BUG
