### ISSUE TITLE
master分支代码缺失

### ISSUE THREAD

**Issue by xxw2016** [purang-fintech/seppb#4]
![image](https://user-images.githubusercontent.com/21070486/71246341-6ad6b300-2351-11ea-998c-17848ae2f8c4.png)

**Comment by purang-fintech** [comment]
……

**Comment by xxw2016** [comment]
好的，下面那个描述了，哈哈

**Comment by xxw2016** [comment]
![image](https://user-images.githubusercontent.com/21070486/71247416-b5592f00-2353-11ea-842a-f2cb277d1fc2.png)


import com.pr.sepp.mgr.system.model.SystemSetting 这个文件还有方法没有提交吧，提示没找到~~
jenkinsConfig.getBuilderServer()等

**Comment by purang-fintech** [comment]
> ![image](https://user-images.githubusercontent.com/21070486/71247416-b5592f00-2353-11ea-842a-f2cb277d1fc2.png)
> 
> import com.pr.sepp.mgr.system.model.SystemSetting 这个文件还有方法没有提交吧，提示没找到~~
> jenkinsConfig.getBuilderServer()等

本地IDE吗，估计你没安装lombok插件吧

**Comment by xxw2016** [comment]
对，本地IDE，应该是文件缺失~提示

**Comment by purang-fintech** [comment]
> 对，本地IDE，应该是文件缺失~提示

你先装好lombok插件~~~

**Comment by xxw2016** [comment]
![image](https://user-images.githubusercontent.com/21070486/71248742-927c4a00-2356-11ea-8afb-7ca389e9f1b0.png)
这个是需要本地安装jenkins ?,你们的qq群通过下~方便哈哈
![image](https://user-images.githubusercontent.com/21070486/71248763-a1fb9300-2356-11ea-9326-4ea8963d297d.png)

**Comment by xxw2016** [comment]
\seppb\src\main\java\com\pr\sepp\utils\jenkins\JenkinsClientManager.java 文件的
jenkinsClientProvider.getBuildJenkinsClientProviderMap() 未找到
